### ISSUE TITLE
Does this code actually work?

### ISSUE THREAD

**Issue by aaronksaunders** [driftyco/ionic-example-cordova-camera#1]
Just a visual review of this code, makes me think that it won't work. Looks like when you added promises to the factory, you did not update the method signature appropriately

This code is passing the options in to the function incorrectly 
  ~~~~
$scope.getPhoto = function() {
    console.log('Getting camera');
    Camera.getPicture().then(function(imageURI) {
      console.log(imageURI);
      $scope.lastPhoto = imageURI;
    }, function(err) {
      console.err(err);
    }, {
      quality: 75,
      targetWidth: 320,
      targetHeight: 320,
      saveToPhotoAlbum: false
    });
~~~~
Shouldn't it look more like this?
~~~~
  $scope.getPhoto = function() {
    console.log('Getting camera');
   
    var options = {
      quality: 75,
      targetWidth: 320,
      targetHeight: 320,
      saveToPhotoAlbum: false
    };

    // passing options in as a parameter
    Camera.getPicture(options).then(function(imageURI) {
      console.log(imageURI);
      $scope.lastPhoto = imageURI;
    }, function(err) {
      console.err(err);
    });
~~~~

**Comment by jues** [comment]
@aaronksaunders is right, the options code won't work! 
Can't believe that bug lives almost a year, without a fix.

**Comment by flomerboy** [comment]
Yeah this should probably get changed!

Confused the heck out of me as a beginner.

**Comment by mlynch** [comment]
sorry about that: https://github.com/driftyco/ionic-example-cordova-camera/commit/b16b1c7baf89d358660957023760dc27f5a2ef46

Also, this project should use ngCordova anyways: http://ngcordova.com/
