### ISSUE TITLE
navigator.camera undefined

### ISSUE THREAD

**Issue by jczaplew** [driftyco/ionic-example-cordova-camera#9]
I couldn't get the cordova camera plugin to work in my app, so I decided to try this example to see what it might be doing differently, but I'm running into the same issue as I was in my app. I followed the instructions as so:

```
git clone https://github.com/driftyco/ionic-example-cordova-camera.git
cd ionic-example-cordova-camera
npm install
ionic serve
```

When I click the button, I see an error `TypeError: Cannot read property 'getPicture' of undefined`, which seems to be thrown because `navigator.camera` is undefined.

I'm sure I'm just missing something, but any assistance would be appreciated. Thanks!

**Comment by SecuriTeam** [comment]
You can not use this plugin in browser using `ionic serve`

You need to test it on emulators or actual devices.

**Comment by jczaplew** [comment]
I tried:

```
ionic platform add ios
ionic build ios
ionic run ios
```

In the iOS Simulator, I still get an error in the system log when I click "Take Photo":

```
May  7 09:18:28 CameraTest[27038]: ACTIVATING
May  7 09:18:28  CameraTest[27038]: Camera.getPicture: source type 1 not available.
```

Perhaps it only works on a real device?

**Comment by jczaplew** [comment]
However, I just tried building it in XCode and the build failed with 18 errors. I then ran:

```
ionic platform remove ios
ionic platform add ios
ionic build ios
```

After that, the build succeeded in XCode and I was able to successfully test on an iPhone.

**Comment by SecuriTeam** [comment]
On android it work with emulators (at least genymotion that I have tried)..
But now since you've mentioned it.. the ngCordova version says it only works on real devices and not in emulators.. Perhaps they were referring to iOS and stock AVDs (Android Virtual Devices).
